#!/bin/bash

if [ $# -ne 1 ] || [ "$1" != "junit" ] && [ "$1" != "local" ]; then
    echo "Usage: $0 [junit|local]"
    exit 1
fi

docker run -it --rm --network alpha-network postgres psql -h alphadb-$1 -p 5432 -U alphadb-$1 -c \
"insert into alpha.user_profile values (1, 'alex', '534b44a19bf18d20b71ecc4eb77c572f', TIMESTAMP '2019-04-02 07:58:28', NULL)"
