CREATE SCHEMA IF NOT EXISTS alpha;
CREATE TABLE IF NOT EXISTS user_profile (
	id INT PRIMARY KEY,
	login VARCHAR (50),
	password CHAR (32),
	created TIMESTAMP WITH TIME ZONE,
	modified TIMESTAMP WITH TIME ZONE
)